name: Automatic Build and Deploy to GitHub Pages

on:
  schedule:
    # Runs every sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    name: Build and Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit and push dist folder
        uses: actions-x/commit@v6
        with:
          email: ${{ secrets.GIT_EMAIL }}
          name: lfcourtney
          files: dist
          message: "Automated build: $(date)"
          force: true
